image: charlesloveman/wacc36:latest

stages:
    - compile
    - front-end
    - back-end

compile:
    stage: compile
    script:
        - make
    artifacts:
        paths:
            - src/antlr/
            - bin/

testSyntax:
    stage: front-end
    script:
        - chmod +x tests/invalid_syntax.sh
        - ./tests/invalid_syntax.sh
    dependencies:
        - compile

testSemantics:
    stage: front-end
    script:
        - chmod +x tests/invalid_semantic.sh
        - ./tests/invalid_semantic.sh
    dependencies:
        - compile

testValid:
    stage: front-end
    script:
        - chmod +x tests/valid.sh
        - ./tests/valid.sh
    dependencies:
        - compile
        