image: charlesloveman/wacc36:latest

stages:
    - compile
    - testSyntax
    - testSemantics
    - testValid

compile:
    stage: compile
    script:
        - make
    artifacts:
        paths:
            - src/antlr/
            - bin/

testSyntax:
    stage: testSyntax
    script:
        - chmod a+x invalid_syntax.sh
        - ./invalid_syntax.sh
    dependencies:
        - compile

testSemantics:
    stage: testSemantics
    script:
        - chmod a+x invalid_semantic.sh
        - ./invalid_semantic.sh
    dependencies:
        - compile
testValid:
    stage: testValid
    script:
        - chmod a+x valid.sh
        - ./valid.sh
    dependencies:
        - compile
